/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#1b110f",
        "on-primary-fixed-variant": "#07521d",
        "on-surface": "#f3deda",
        "on-secondary-fixed": "#201a18",
        "surface-variant": "#3e322f",
        "error": "#ffb4ab",
        "surface-dim": "#1b110f",
        "tertiary": "#ddc1b7",
        "primary-container": "#00350f",
        "on-primary": "#003911",
        "on-secondary": "#352f2d",
        "secondary-fixed-dim": "#cfc4c0",
        "tertiary-fixed-dim": "#ddc1b7",
        "surface-container-low": "#241917",
        "surface-container-high": "#332725",
        "surface-container": "#281d1b",
        "secondary-container": "#4c4542",
        "tertiary-container": "#3a2922",
        "inverse-on-surface": "#3a2e2b",
        "on-primary-container": "#5fa364",
        "on-error": "#690005",
        "primary-fixed": "#abf4ac",
        "surface-container-highest": "#3e322f",
        "surface-tint": "#90d792",
        "on-tertiary": "#3e2c26",
        "primary-fixed-dim": "#90d792",
        "outline": "#9c8d8b",
        "surface-container-lowest": "#150c0a",
        "on-primary-fixed": "#002107",
        "on-surface-variant": "#d3c3c0",
        "outline-variant": "#504442",
        "inverse-primary": "#286b33",
        "secondary": "#cfc4c0",
        "on-secondary-fixed-variant": "#4c4542",
        "on-tertiary-fixed-variant": "#56423b",
        "on-background": "#f3deda",
        "inverse-surface": "#f3deda",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#bdb3af",
        "error-container": "#93000a",
        "surface-bright": "#433634",
        "secondary-fixed": "#ece0dc",
        "on-tertiary-fixed": "#271812",
        "tertiary-fixed": "#fadcd2",
        "surface": "#1b110f",
        "primary": "#90d792",
        "on-tertiary-container": "#a88f86"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "sm": "12px",
        "xs": "4px",
        "margin-desktop": "32px",
        "md": "24px",
        "xl": "64px",
        "lg": "40px",
        "gutter": "16px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "label-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "body-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-md": ["Atkinson Hyperlegible Next", "sans-serif"],
        "label-sm": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-sm": ["Sora", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
