import { CropSuggestion, SoilTestProfile } from '../types/farm';

export interface FieldConditionContext {
  soilProfile: SoilTestProfile;
  acres: number;
  waterAvailability: 'High' | 'Moderate' | 'Low';
  district: string;
  season?: 'Kharif' | 'Rabi' | 'Summer';
}

export const COMPREHENSIVE_CROP_CATALOG: CropSuggestion[] = [
  {
    cropName: 'Groundnut (Kharif/Rabi)',
    cropDurationDays: 110,
    waterRequirement: 'Low',
    soilSuitability: 'Excellent for Red Sandy Loam and well-drained soils (pH 6.2 - 7.5)',
    climateSuitability: 'Thrives in warm, dry weather with moderate temperatures (24°C - 32°C)',
    expectedExpenditurePerAcre: 22000,
    expectedYieldPerAcre: '1.2 - 1.6 tonnes',
    expectedRevenuePerAcre: 68000,
    expectedProfitPerAcre: 46000,
    majorDiseaseRisks: ['Tikka Leaf Spot', 'Collar Rot', 'Rust'],
    majorWeedRisks: ['Cyperus rotundus (Nut Grass)', 'Digitaria', 'Amaranthus'],
    suitabilityScore: 'High',
    suitabilityReason: 'Low water requirement, restores soil nitrogen, high profit margin in regional mandis.',
    icon: 'eco',
    suitability: 'High',
    reason: 'Restores nitrogen and requires less water post-monsoon.',
  },
  {
    cropName: 'Maize (Winter / Kharif)',
    cropDurationDays: 105,
    waterRequirement: 'Medium',
    soilSuitability: 'Ideal in deep, fertile loams with good drainage and balanced organic carbon',
    climateSuitability: 'Warm sunshine and moderate moisture during vegetative and tasseling phases',
    expectedExpenditurePerAcre: 18500,
    expectedYieldPerAcre: '2.8 - 3.4 tonnes',
    expectedRevenuePerAcre: 62000,
    expectedProfitPerAcre: 43500,
    majorDiseaseRisks: ['Fall Armyworm', 'Turcicum Leaf Blight', 'Stalk Rot'],
    majorWeedRisks: ['Echinochloa', 'Trianthema portulacastrum (Horse Purslane)', 'Bermuda Grass'],
    suitabilityScore: 'High',
    suitabilityReason: 'Stable feed and industrial market demand with high yield response to organic carbon.',
    icon: 'nutrition',
    suitability: 'High',
    reason: 'High biomass yield with excellent grain pricing in local mandis.',
  },
  {
    cropName: 'Red Gram / Pigeon Pea (Kandulu)',
    cropDurationDays: 150,
    waterRequirement: 'Low',
    soilSuitability: 'Highly resilient in medium to deep black & red soils; drought tolerant',
    climateSuitability: 'Semi-arid tropical conditions with tolerance to intermittent dry spells',
    expectedExpenditurePerAcre: 14000,
    expectedYieldPerAcre: '0.8 - 1.1 tonnes',
    expectedRevenuePerAcre: 58000,
    expectedProfitPerAcre: 44000,
    majorDiseaseRisks: ['Fusarium Wilt', 'Sterility Mosaic', 'Pod Borer (Helicoverpa)'],
    majorWeedRisks: ['Parthenium', 'Digera arvensis', 'Cynodon dactylon'],
    suitabilityScore: 'High',
    suitabilityReason: 'Excellent intercropping pulse; deep taproot breaks hard soil layers and fixes atmospheric nitrogen.',
    icon: 'grass',
    suitability: 'High',
    reason: 'Drought-tolerant leguminous crop with high MSP market support.',
  },
  {
    cropName: 'Cotton (Bt Hybrid)',
    cropDurationDays: 160,
    waterRequirement: 'Medium',
    soilSuitability: 'Best in deep Black Cotton (Regur) soils with good water-holding capacity',
    climateSuitability: 'Long frost-free warm season with dry picking period',
    expectedExpenditurePerAcre: 28000,
    expectedYieldPerAcre: '1.4 - 1.8 tonnes',
    expectedRevenuePerAcre: 84000,
    expectedProfitPerAcre: 56000,
    majorDiseaseRisks: ['Pink Bollworm', 'Alternaria Leaf Spot', 'Bacterial Blight'],
    majorWeedRisks: ['Trianthema', 'Celosia', 'Cyperus'],
    suitabilityScore: 'Moderate',
    suitabilityReason: 'High revenue potential; requires intensive pest scouting during flowering & boll development.',
    icon: 'filter_vintage',
    suitability: 'Moderate',
    reason: 'Strong commodity demand in Guntur/Warangal with intensive bollworm management.',
  },
  {
    cropName: 'Chillies (Teja / Wonderhot)',
    cropDurationDays: 150,
    waterRequirement: 'Medium',
    soilSuitability: 'Fertile well-drained loams rich in organic matter (pH 6.5 - 7.5)',
    climateSuitability: 'Warm, humid climate during growth; dry weather during fruit ripening',
    expectedExpenditurePerAcre: 45000,
    expectedYieldPerAcre: '1.8 - 2.2 tonnes (Dry)',
    expectedRevenuePerAcre: 160000,
    expectedProfitPerAcre: 115000,
    majorDiseaseRisks: ['Chilli Leaf Curl Virus', 'Anthracnose Fruit Rot', 'Thrips Infestation'],
    majorWeedRisks: ['Echinochloa', 'Amaranthus viridis', 'Nut Grass'],
    suitabilityScore: 'Moderate',
    suitabilityReason: 'Extremely high profit margin; requires attentive pest & viral vector management.',
    icon: 'local_fire_department',
    suitability: 'Moderate',
    reason: 'High economic value in export hubs, but needs drip irrigation and sticky trap protection.',
  },
  {
    cropName: 'Paddy (BPT 5204 / Samba Mahsuri)',
    cropDurationDays: 125,
    waterRequirement: 'High',
    soilSuitability: 'Clay loams with impervious subsoil capable of holding standing water',
    climateSuitability: 'Warm humid climate (22°C - 34°C) with plenty of solar radiation',
    expectedExpenditurePerAcre: 25000,
    expectedYieldPerAcre: '2.4 - 3.0 tonnes',
    expectedRevenuePerAcre: 72000,
    expectedProfitPerAcre: 47000,
    majorDiseaseRisks: ['Paddy Blast', 'Brown Spot', 'Sheath Blight', 'Stem Borer'],
    majorWeedRisks: ['Echinochloa crus-galli', 'Eclipta alba', 'Cyperus difformis'],
    suitabilityScore: 'High',
    suitabilityReason: 'Traditional staple with guaranteed local APMC mandi procurement and high consumer demand.',
    icon: 'water',
    suitability: 'High',
    reason: 'Proven crop with dependable yield if water availability is continuous.',
  },
  {
    cropName: 'Bengal Gram / Chickpea (Sanagalu)',
    cropDurationDays: 95,
    waterRequirement: 'Low',
    soilSuitability: 'Residual moisture black soils; does not tolerate waterlogging',
    climateSuitability: 'Cool, dry winter conditions with bright sunshine',
    expectedExpenditurePerAcre: 12500,
    expectedYieldPerAcre: '0.8 - 1.2 tonnes',
    expectedRevenuePerAcre: 52000,
    expectedProfitPerAcre: 39500,
    majorDiseaseRisks: ['Fusarium Wilt', 'Dry Root Rot', 'Helicoverpa Pod Borer'],
    majorWeedRisks: ['Chenopodium', 'Asphodelus', 'Convolvulus'],
    suitabilityScore: 'High',
    suitabilityReason: 'Short duration rabi pulse utilizing residual moisture; low input expenditure.',
    icon: 'grain',
    suitability: 'High',
    reason: 'Ideal second crop requiring zero extra irrigation in moisture-retentive black soils.',
  },
];

/**
 * Generates suitable crop options based on soil test profile and field conditions
 */
export function getCropSuggestionsForField(context: FieldConditionContext): CropSuggestion[] {
  return COMPREHENSIVE_CROP_CATALOG;
}
