
import { Farmer, FieldBoundary, CropHistoryRecord, MarketRate, CropSuggestion, DayCropUpdate } from '../types/farm';

import {
  Farmer,
  Field,
  FieldBoundary,
  CropHistoryRecord,
  MarketRate,
  CropSuggestion,
  SoilTestProfile,
  PreviousCropRecord,
  LiveSensors,
  MotorStatus,
} from '../types/farm';
import { calculateCropAgeDays, getGrowthStageForCrop } from './cropStageService';

export const INITIAL_SOIL_PROFILE_FIELD_01: SoilTestProfile = {
  soilType: 'Clay Loam (Alluvial)',
  testedAt: '10 July 2026',
  labName: 'District Soil Testing Lab, Nellore',
  ph: 6.8,
  phInterpretation: 'Suitable (Optimal)',
  nitrogenKgHa: 240,
  nitrogenInterpretation: 'Medium (Adequate)',
  phosphorusKgHa: 28,
  phosphorusInterpretation: 'High (Optimal)',
  potassiumKgHa: 195,
  potassiumInterpretation: 'Medium (Adequate)',
  organicCarbonPercent: 0.55,
  organicCarbonInterpretation: 'Medium',
  electricalConductivityDsM: 0.72,
  ecInterpretation: 'Normal / Safe',
  soilMoisturePercent: 34,
};

export const INITIAL_SOIL_PROFILE_FIELD_02: SoilTestProfile = {
  soilType: 'Red Sandy Loam',
  testedAt: '18 July 2026',
  labName: 'Rythu Bharosa Kendra, Kovur',
  ph: 6.4,
  phInterpretation: 'Suitable (Optimal)',
  nitrogenKgHa: 180,
  nitrogenInterpretation: 'Low',
  phosphorusKgHa: 22,
  phosphorusInterpretation: 'Medium',
  potassiumKgHa: 165,
  potassiumInterpretation: 'Medium (Adequate)',
  organicCarbonPercent: 0.45,
  organicCarbonInterpretation: 'Low',
  electricalConductivityDsM: 0.38,
  ecInterpretation: 'Normal / Safe',
  soilMoisturePercent: 38,
};

export const INITIAL_SOIL_PROFILE_FIELD_03: SoilTestProfile = {
  soilType: 'Medium Deep Black Cotton Soil',
  testedAt: '05 June 2026',
  labName: 'Regional Agri Research Station, Nellore',
  ph: 7.5,
  phInterpretation: 'Suitable (Optimal)',
  nitrogenKgHa: 260,
  nitrogenInterpretation: 'Medium (Adequate)',
  phosphorusKgHa: 31,
  phosphorusInterpretation: 'High (Optimal)',
  potassiumKgHa: 280,
  potassiumInterpretation: 'High',
  organicCarbonPercent: 0.65,
  organicCarbonInterpretation: 'High',
  electricalConductivityDsM: 0.61,
  ecInterpretation: 'Normal / Safe',
  soilMoisturePercent: 42,
};

export const INITIAL_PREVIOUS_CROP_FIELD_01: PreviousCropRecord[] = [
  {
    id: 'pc-01',
    cropName: 'Paddy',
    cropVariety: 'BPT 5204 (Samba Mahsuri)',
    sowingDate: '2025-07-10',
    harvestDate: '2025-11-20',
    expectedYieldTons: 4.8,
    actualYieldTons: 4.1,
    efficiencyPercent: 85,
    mainLossFactor: 'Water Deficit & Stem Borer Infestation',
    problemsEncountered: [
      { category: 'pest', description: 'Yellow Stem Borer attack at panicle initiation', impactTons: 0.3 },
      { category: 'irrigation', description: 'Canal release delay during reproductive phase', impactTons: 0.2 },
      { category: 'disease', description: 'Brown spot on lower leaves', impactTons: 0.2 },
    ],
  },
  {
    id: 'pc-02',
    cropName: 'Black Gram (Minumulu)',
    cropVariety: 'PU 31',
    sowingDate: '2024-12-15',
    harvestDate: '2025-03-05',
    expectedYieldTons: 1.2,
    actualYieldTons: 1.1,
    efficiencyPercent: 91,
    mainLossFactor: 'Mild Powdery Mildew',
    problemsEncountered: [
      { category: 'disease', description: 'Powdery mildew in late flowering', impactTons: 0.1 },
    ],
  },
];

export const INITIAL_PREVIOUS_CROP_FIELD_02: PreviousCropRecord[] = [
  {
    id: 'pc-03',
    cropName: 'Black Gram',
    cropVariety: 'LBG 752',
    sowingDate: '2025-11-25',
    harvestDate: '2026-02-28',
    expectedYieldTons: 1.1,
    actualYieldTons: 0.95,
    efficiencyPercent: 86,
    mainLossFactor: 'Yellow Mosaic Virus transmitted by whiteflies',
    problemsEncountered: [
      { category: 'disease', description: 'Yellow Mosaic Virus in patches', impactTons: 0.15 },
    ],
  },
];

export const INITIAL_PREVIOUS_CROP_FIELD_03: PreviousCropRecord[] = [
  {
    id: 'pc-04',
    cropName: 'Maize',
    cropVariety: 'DKC 9108',
    sowingDate: '2024-10-10',
    harvestDate: '2025-01-25',
    expectedYieldTons: 3.5,
    actualYieldTons: 3.1,
    efficiencyPercent: 88,
    mainLossFactor: 'Fall Armyworm whorl damage',
    problemsEncountered: [
      { category: 'pest', description: 'Fall Armyworm damage during knee-high stage', impactTons: 0.3 },
      { category: 'weather', description: 'Unseasonal drizzle during harvesting', impactTons: 0.1 },
    ],
  },
];

export const INITIAL_FIELD_01_SENSORS: LiveSensors = {
  fieldId: 'field-01',
  overallMoisture: 34,
  airTemp: 34,
  humidity: 61,
  airQuality: 'Good',
  cropHealthPercent: 78,
  cropHealthStatus: 'ATTENTION',
  actionRequired: 'Your soil is dry in Sector 03 (21%). Irrigation is required.',
  nodes: [
    {
      id: 'S01',
      name: 'Sector 01',
      sector: 'North Plot',
      status: 'normal',
      moisture: 42,
      temp: 33,
      humidity: 62,
      airQuality: 'Good',
      recommendation: 'Moisture level good',
      x: 35,
      y: 30,
      lastUpdated: 'Just now',
    },
    {
      id: 'S02',
      name: 'Sector 02',
      sector: 'West Plot',
      status: 'normal',
      moisture: 36,
      temp: 34,
      humidity: 60,
      airQuality: 'Good',
      recommendation: 'Moisture level good',
      x: 70,
      y: 40,
      lastUpdated: 'Just now',
    },
    {
      id: 'S03',
      name: 'Sector 03',
      sector: 'East Plot',
      status: 'critical',
      moisture: 21,
      temp: 36,
      humidity: 54,
      airQuality: 'Fair',
      recommendation: 'Soil is dry! Start irrigation now.',
      x: 65,
      y: 65,
      lastUpdated: 'Just now',
    },
    {
      id: 'S04',
      name: 'Sector 04',
      sector: 'South Plot',
      status: 'normal',
      moisture: 39,
      temp: 34,
      humidity: 61,
      airQuality: 'Good',
      recommendation: 'Moisture level good',
      x: 42,
      y: 58,
      lastUpdated: 'Just now',
    },
  ],
};

export const INITIAL_FIELD_02_SENSORS: LiveSensors = {
  fieldId: 'field-02',
  overallMoisture: 41,
  airTemp: 33,
  humidity: 58,
  airQuality: 'Good',
  cropHealthPercent: 92,
  cropHealthStatus: 'GOOD',
  actionRequired: null,
  nodes: [
    {
      id: 'F2-S01',
      name: 'Sector 01',
      sector: 'North Ridge',
      status: 'normal',
      moisture: 40,
      temp: 33,
      humidity: 58,
      recommendation: 'Optimal pegging moisture',
      x: 30,
      y: 35,
      lastUpdated: 'Just now',
    },
    {
      id: 'F2-S02',
      name: 'Sector 02',
      sector: 'South Slope',
      status: 'normal',
      moisture: 43,
      temp: 32,
      humidity: 59,
      recommendation: 'Healthy root zone',
      x: 65,
      y: 60,
      lastUpdated: 'Just now',
    },
  ],
};

export const INITIAL_FIELD_03_SENSORS: LiveSensors = {
  fieldId: 'field-03',
  overallMoisture: 45,
  airTemp: 34,
  humidity: 64,
  airQuality: 'Good',
  cropHealthPercent: 86,
  cropHealthStatus: 'GOOD',
  actionRequired: null,
  nodes: [
    {
      id: 'F3-S01',
      name: 'Sector 01',
      sector: 'Block A (Flowering)',
      status: 'normal',
      moisture: 46,
      temp: 34,
      humidity: 63,
      recommendation: 'Boll formation moisture good',
      x: 40,
      y: 40,
      lastUpdated: 'Just now',
    },
    {
      id: 'F3-S02',
      name: 'Sector 02',
      sector: 'Block B (Boll Setting)',
      status: 'normal',
      moisture: 44,
      temp: 34,
      humidity: 65,
      recommendation: 'Maintain regular drip cycle',
      x: 75,
      y: 55,
      lastUpdated: 'Just now',
    },
  ],
};

export const INITIAL_MOTOR_STATUS: MotorStatus = {
  isOnline: true,
  isRunning: false,
  activeSectorId: null,
  isSimulated: true,
  history: [
    {
      id: 'irr-1',
      timestamp: '2026-08-29 06:30 AM',
      action: 'stop',
      sector: 'Sector 01 (North Plot)',
      durationMinutes: 45,
    },
    {
      id: 'irr-2',
      timestamp: '2026-08-27 05:00 PM',
      action: 'stop',
      sector: 'Sector 04 (South Plot)',
      durationMinutes: 30,
    },
  ],
};

export const INITIAL_FIELDS: Field[] = [
  {
    id: 'field-01',
    name: 'Field 01 - Paddy Main Plot',
    acres: 2.4,
    location: {
      district: 'Nellore',
      village: 'Kovur',
      mandal: 'Kovur Mandal',
    },
    boundary: {
      id: 'field-01',
      name: 'Field 01 - Paddy Main Plot',
      acres: 2.4,
      isRecorded: true,
      savedAt: '2026-07-15 10:30 AM',
      points: [
        { x: 20, y: 80, lat: 14.5012, lng: 79.9812 },
        { x: 30, y: 30, lat: 14.5045, lng: 79.9825 },
        { x: 70, y: 20, lat: 14.505, lng: 79.987 },
        { x: 85, y: 60, lat: 14.502, lng: 79.9885 },
        { x: 60, y: 90, lat: 14.4995, lng: 79.985 },
      ],
    },
    activeCrop: 'Paddy',
    cropVariety: 'BPT 5204',
    sowingDate: '2026-07-14',
    cropAgeDays: calculateCropAgeDays('2026-07-14'),
    growthStage: getGrowthStageForCrop('Paddy', calculateCropAgeDays('2026-07-14')),
    soilProfile: INITIAL_SOIL_PROFILE_FIELD_01,
    previousCropHistory: INITIAL_PREVIOUS_CROP_FIELD_01,
    sensors: INITIAL_FIELD_01_SENSORS,
    registeredDiseases: [],
    motorStatus: INITIAL_MOTOR_STATUS,
  },
  {
    id: 'field-02',
    name: 'Field 02 - North Orchard & Pulses',
    acres: 1.8,
    location: {
      district: 'Nellore',
      village: 'Kovur North',
      mandal: 'Kovur Mandal',
    },
    boundary: {
      id: 'field-02',
      name: 'Field 02 - North Orchard & Pulses',
      acres: 1.8,
      isRecorded: true,
      savedAt: '2026-08-05 09:15 AM',
      points: [
        { x: 25, y: 70, lat: 14.511, lng: 79.983 },
        { x: 35, y: 25, lat: 14.514, lng: 79.984 },
        { x: 75, y: 30, lat: 14.515, lng: 79.989 },
        { x: 65, y: 80, lat: 14.51, lng: 79.987 },
      ],
    },
    activeCrop: 'Groundnut',
    cropVariety: 'Kadiri 6',
    sowingDate: '2026-08-02',
    cropAgeDays: calculateCropAgeDays('2026-08-02'),
    growthStage: getGrowthStageForCrop('Groundnut', calculateCropAgeDays('2026-08-02')),
    soilProfile: INITIAL_SOIL_PROFILE_FIELD_02,
    previousCropHistory: INITIAL_PREVIOUS_CROP_FIELD_02,
    sensors: INITIAL_FIELD_02_SENSORS,
    registeredDiseases: [],
    motorStatus: { ...INITIAL_MOTOR_STATUS, isRunning: false },
  },
  {
    id: 'field-03',
    name: 'Field 03 - West Commercial Plot',
    acres: 3.0,
    location: {
      district: 'Nellore',
      village: 'Damaramadugu',
      mandal: 'Buchireddipalem',
    },
    boundary: {
      id: 'field-03',
      name: 'Field 03 - West Commercial Plot',
      acres: 3.0,
      isRecorded: true,
      savedAt: '2026-06-30 04:00 PM',
      points: [
        { x: 15, y: 85, lat: 14.495, lng: 79.972 },
        { x: 25, y: 20, lat: 14.498, lng: 79.974 },
        { x: 80, y: 15, lat: 14.499, lng: 79.98 },
        { x: 90, y: 75, lat: 14.496, lng: 79.982 },
      ],
    },
    activeCrop: 'Cotton',
    cropVariety: 'Rasi Bt II',
    sowingDate: '2026-06-25',
    cropAgeDays: calculateCropAgeDays('2026-06-25'),
    growthStage: getGrowthStageForCrop('Cotton', calculateCropAgeDays('2026-06-25')),
    soilProfile: INITIAL_SOIL_PROFILE_FIELD_03,
    previousCropHistory: INITIAL_PREVIOUS_CROP_FIELD_03,
    sensors: INITIAL_FIELD_03_SENSORS,
    registeredDiseases: [],
    motorStatus: { ...INITIAL_MOTOR_STATUS, isRunning: false },
  },
];


export const INITIAL_FARMER: Farmer = {
  id: 'farmer-raju',
  name: 'Raju Garu',
  phone: '+91 98765 43210',
  district: 'Nellore',
  village: 'Kovur',
  activeFieldId: 'field-01',
  fields: INITIAL_FIELDS,
  // Legacy getters
  fieldName: 'Field 01 - Paddy Main Plot',
  activeCrop: 'Paddy',
  sowingDate: '2026-07-14',
  cropStage: 'Budding Stage',
  cropDay: 47,
  totalCropDays: 120,
};


export const INITIAL_DAY_UPDATES: DayCropUpdate[] = [
  {
    day: 47,
    date: 'Aug 29 (Today)',
    stage: 'Budding Stage',
    title: 'Apical Meristem Transition & Bud Development',
    summary: 'Active panicle primordium initiation confirmed. Shoot apex transition progressing with vigorous green foliage and strong root absorption.',
    tasks: [
      'Visual inspection of apical shoot meristem for panicle elongation',
      'Measured canopy height (48.2 cm) across all 4 field sectors',
      'Checked automated moisture sensor telemetry (42% average)',
      'Verified zero leaf folder or gall midge infestation',
    ],
    inputsApplied: 'Targeted water channel replenishment (4 cm standing water)',
    category: 'inspection',
    status: 'optimal',
    icon: 'spa',
    healthPercent: 88,
  },
  {
    day: 46,
    date: 'Aug 28 (Yesterday)',
    stage: 'Budding Stage',
    title: 'Post-Irrigation Moisture Recovery & Soil Stabilization',
    summary: 'Automated irrigation cycle executed in Sector 03. Soil moisture restored from 21% to 42%, maintaining ideal root hydration.',
    tasks: [
      'Executed scheduled smart motor run in Sector 03 for 45 minutes',
      'Verified uniform water diffusion along sub-channel lines',
      'Recorded post-irrigation sensor stabilization in telemetry log',
    ],
    inputsApplied: 'Smart drip & channel irrigation (12,000 Liters in Sector 03)',
    category: 'irrigation',
    status: 'action_taken',
    icon: 'water_drop',
    healthPercent: 86,
  },
  {
    day: 45,
    date: 'Aug 27',
    stage: 'Budding Stage',
    title: 'Pre-Budding Foliar & Stem Thickness Inspection',
    summary: 'Internode elongation proceeding smoothly. Stem base thickness measured 1.1 cm; leaf chlorophyll index healthy.',
    tasks: [
      'Foliar health audit across 50 random sample hills',
      'Scouted lower stems for sheath rot and bacterial leaf blight',
      'Checked field bund perimeter for rodent activity',
    ],
    inputsApplied: 'None (Observation day)',
    category: 'inspection',
    status: 'optimal',
    icon: 'check_circle',
    healthPercent: 87,
  },
  {
    day: 44,
    date: 'Aug 26',
    stage: 'Budding Stage',
    title: 'Micro-Nutrient Boron & Zinc Foliar Spray',
    summary: 'Applied targeted foliar booster to promote uniform panicle differentiation and prevent spikelet sterility.',
    tasks: [
      'Sprayed Chelated Zinc (0.5 g/L) + Solubor (1 g/L) during early morning',
      'Inspected spray nozzle coverage across 2.4 acres',
      'Recorded air temperature (28°C) and humidity (64%) during spray',
    ],
    inputsApplied: 'Zinc EDTA + Boron booster (500g / 200L water)',
    category: 'fertilizer',
    status: 'action_taken',
    icon: 'science',
    healthPercent: 86,
  },
  {
    day: 43,
    date: 'Aug 25',
    stage: 'Budding Stage',
    title: 'Water Level Calibration for Panicle Initiation',
    summary: 'Raised standing water level to 4-5 cm to cushion emerging panicles against temperature fluctuations.',
    tasks: [
      'Regulated sluice gates between Sector 01 and Sector 02',
      'Maintained continuous standing water blanket across all sectors',
      'Checked electrical conductivity (EC) of flood water',
    ],
    inputsApplied: 'Fresh canal water intake (4 cm depth)',
    category: 'irrigation',
    status: 'optimal',
    icon: 'water',
    healthPercent: 87,
  },
  {
    day: 42,
    date: 'Aug 24',
    stage: 'Budding Stage',
    title: 'Potassium Nitrate (13-0-45) Panicle Top-Dress',
    summary: 'Applied balanced nitrogen-potassium booster to strengthen developing embryonic flower clusters.',
    tasks: [
      'Broadcasting of Potassium Nitrate top-dress in moist soil',
      'Field scouted for early stem borer dead hearts',
      'Cleared weed escapes near field irrigation inlets',
    ],
    inputsApplied: 'Potassium Nitrate 13-0-45 (15 kg/acre)',
    category: 'fertilizer',
    status: 'action_taken',
    icon: 'grain',
    healthPercent: 85,
  },
  {
    day: 41,
    date: 'Aug 23',
    stage: 'Budding Stage',
    title: 'Panicle Primordium Initiation (Budding Stage Start)',
    summary: 'Microscopic dissection of main tiller stem revealed 1.5mm greenish panicle primordium. Crop officially entered Budding Stage.',
    tasks: [
      'Destructive sampling of 3 representative tillers to confirm PI stage',
      'Measured transition from vegetative tillering to reproductive phase',
      'Logged transition date in FarmAI digital agronomy tracker',
    ],
    inputsApplied: 'None (Phenological Transition)',
    category: 'inspection',
    status: 'optimal',
    icon: 'psychiatry',
    healthPercent: 86,
  },
  {
    day: 40,
    date: 'Aug 22',
    stage: 'Vegetative Stage',
    title: 'Final Vegetative Canopy Audit & Weed Clean-up',
    summary: 'Vegetative phase concluding with 15 productive tillers per hill. Hand-pulled rogue Echinochloa grass along sector margins.',
    tasks: [
      'Spot weeding along sector boundary ditches and bunds',
      'Confirmed full canopy ground cover (95% light interception)',
      'Verified zero lodging risk or stem weakness',
    ],
    inputsApplied: 'Manual labor hand-weeding',
    category: 'weeding',
    status: 'action_taken',
    icon: 'grass',
    healthPercent: 85,
  },
  {
    day: 39,
    date: 'Aug 21',
    stage: 'Vegetative Stage',
    title: 'Insect Light Trap & Pest Scouting',
    summary: 'Monitored nocturnal pest flight. Minor green leafhopper catches observed, well below the economic threshold level (ETL).',
    tasks: [
      'Inspected solar light trap counts (4 leafhoppers, 1 moth)',
      'Scouted 20 hills for brown plant hopper (BPH) nymphs at base',
      'Recorded negative BPH presence at water line',
    ],
    inputsApplied: 'Pheromone & Light Trap Maintenance',
    category: 'pest_control',
    status: 'optimal',
    icon: 'pest_control',
    healthPercent: 85,
  },
  {
    day: 38,
    date: 'Aug 20',
    stage: 'Vegetative Stage',
    title: 'NPK 19:19:19 Foliar Booster Application',
    summary: 'Applied balanced water-soluble foliar spray to provide immediate macro-nutrients before internode elongation.',
    tasks: [
      'Sprayed 19:19:19 NPK solution (5 g/L) via tractor-mounted boom',
      'Checked spray uniformity across 2.4 acres',
      'Confirmed leaves dry before afternoon heat peak',
    ],
    inputsApplied: 'NPK 19-19-19 Soluble (2.5 kg total)',
    category: 'fertilizer',
    status: 'action_taken',
    icon: 'science',
    healthPercent: 85,
  },
  {
    day: 37,
    date: 'Aug 19',
    stage: 'Vegetative Stage',
    title: 'Peak Tillering Phase Confirmation',
    summary: 'Highest tiller density achieved with 14-16 strong, vigorous tillers per hill. Plant height reached 42 cm.',
    tasks: [
      'Counted effective tillers across 10 sample grids',
      'Measured plant height and shoot diameter',
      'Assessed inter-row space closure',
    ],
    inputsApplied: 'None',
    category: 'inspection',
    status: 'optimal',
    icon: 'yard',
    healthPercent: 85,
  },
  {
    day: 36,
    date: 'Aug 18',
    stage: 'Vegetative Stage',
    title: 'Controlled Re-flooding Post-Aeration',
    summary: 'Re-introduced fresh canal water to 3 cm depth after 24-hour soil aeration drying window.',
    tasks: [
      'Opened main inlet gate for fresh canal water inflow',
      'Monitored water depth across all 4 sector nodes',
      'Confirmed soil moisture recovery to 46%',
    ],
    inputsApplied: 'Canal irrigation water (3 cm layer)',
    category: 'irrigation',
    status: 'action_taken',
    icon: 'water_drop',
    healthPercent: 84,
  },
  {
    day: 35,
    date: 'Aug 17',
    stage: 'Vegetative Stage',
    title: 'Alternate Wetting & Drying (AWD) Aeration Day',
    summary: 'Allowed field surface to dry slightly to encourage deep geotropic root extension and prevent root rot.',
    tasks: [
      'Measured field tube water depth (-2 cm below soil surface)',
      'Checked for fine hairline soil fissures (ideal aeration cue)',
      'Examined root tips for healthy white coloration',
    ],
    inputsApplied: 'AWD Dry Cycle (No irrigation)',
    category: 'soil_check',
    status: 'optimal',
    icon: 'air',
    healthPercent: 84,
  },
  {
    day: 34,
    date: 'Aug 16',
    stage: 'Vegetative Stage',
    title: 'AWD Cycle Initiation & Sensor Baseline Check',
    summary: 'Commenced scheduled water management cycle. Calibrated moisture probe sensors across Sectors 01-04.',
    tasks: [
      'Placed perforated field water tubes for AWD depth monitoring',
      'Recorded baseline moisture levels in database',
      'Checked field bund integrity',
    ],
    inputsApplied: 'Sensor calibration',
    category: 'soil_check',
    status: 'optimal',
    icon: 'sensors',
    healthPercent: 84,
  },
  {
    day: 33,
    date: 'Aug 15',
    stage: 'Vegetative Stage',
    title: 'Fungal Pathogen & Leaf Blast Inspection',
    summary: 'Detailed examination of older leaves and tillers for spindle-shaped blast spots and brown spot fungus. Zero disease found.',
    tasks: [
      'Inspected 100 leaf blades for Pyricularia oryzae (Blast)',
      'Monitored relative humidity (62%) and night dew duration',
      'Confirmed prophylactic health clearance',
    ],
    inputsApplied: 'Preventive visual pathology survey',
    category: 'inspection',
    status: 'optimal',
    icon: 'coronavirus',
    healthPercent: 84,
  },
  {
    day: 32,
    date: 'Aug 14',
    stage: 'Vegetative Stage',
    title: 'Manual Weed Extraction along Sector Bunds',
    summary: 'Extracted surviving sedges (Cyperus iria) and broadleaf weeds before they compete for top-dress nutrients.',
    tasks: [
      'Manual field rogueing across Sectors 01 to 04',
      'Cleaned weed biomass out of drainage furrows',
      'Applied bund trimmings as soil mulch',
    ],
    inputsApplied: 'Manual weeding',
    category: 'weeding',
    status: 'action_taken',
    icon: 'grass',
    healthPercent: 84,
  },
  {
    day: 31,
    date: 'Aug 13',
    stage: 'Vegetative Stage',
    title: 'Second Nitrogen Top-Dress (Urea + MOP)',
    summary: 'Applied second split dose of Urea and Muriate of Potash to sustain active tillering.',
    tasks: [
      'Broadcasting of Urea (25 kg/acre) + MOP (15 kg/acre)',
      'Water drained to thin film before broadcasting to avoid nutrient runoff',
      'Re-impounded water after 12 hours',
    ],
    inputsApplied: 'Urea (60 kg) + MOP (36 kg) for 2.4 acres',
    category: 'fertilizer',
    status: 'action_taken',
    icon: 'grain',
    healthPercent: 83,
  },
  {
    day: 30,
    date: 'Aug 12',
    stage: 'Vegetative Stage',
    title: 'Mid-Vegetative Growth & Canopy Assessment',
    summary: 'Tillers per hill reached 12. Plant height measured at 36 cm. Canopy density vigorous with deep green coloration.',
    tasks: [
      'Recorded tiller count and leaf area expansion',
      'Checked soil pH (6.8) and electrical conductivity',
      'Took aerial drone RGB survey photo for growth modeling',
    ],
    inputsApplied: 'Drone growth mapping',
    category: 'inspection',
    status: 'optimal',
    icon: 'analytics',
    healthPercent: 84,
  },
  {
    day: 29,
    date: 'Aug 11',
    stage: 'Vegetative Stage',
    title: 'Secondary Tiller Emergence Audit',
    summary: 'Secondary tillers emerging rapidly from basal nodes. Root depth increased to 12 cm.',
    tasks: [
      'Sampled root depth and lateral branching',
      'Checked moisture consistency across Sector 02 and 03',
      'Confirmed zero fertilizer burn symptoms',
    ],
    inputsApplied: 'None',
    category: 'inspection',
    status: 'optimal',
    icon: 'yard',
    healthPercent: 83,
  },
  {
    day: 28,
    date: 'Aug 10',
    stage: 'Vegetative Stage',
    title: 'Yellow Stem Borer Egg Mass Scouting',
    summary: 'Scouted leaf tips across field for buff-colored stem borer egg masses. All sample areas clear.',
    tasks: [
      'Inspected 60 random leaf tips for egg clusters',
      'Checked tiller base for entry holes or frass',
      'Maintained light trap monitoring routine',
    ],
    inputsApplied: 'Pest monitoring',
    category: 'pest_control',
    status: 'optimal',
    icon: 'bug_report',
    healthPercent: 83,
  },
  {
    day: 27,
    date: 'Aug 09',
    stage: 'Vegetative Stage',
    title: 'Automated Irrigation Calibration in Sectors 01 & 02',
    summary: 'Tested automated soil moisture solenoid valves in Sectors 01 and 02. Flow rate and pressure verified.',
    tasks: [
      'Ran automated valve actuation test for 20 minutes',
      'Checked flow sensor meters and moisture jump from 32% to 45%',
      'Cleaned inline disk filter on irrigation line',
    ],
    inputsApplied: 'Channel irrigation test (4,000 Liters)',
    category: 'irrigation',
    status: 'action_taken',
    icon: 'water_drop',
    healthPercent: 83,
  },
  {
    day: 26,
    date: 'Aug 08',
    stage: 'Vegetative Stage',
    title: 'Drone Multispectral Weed & NDVI Scan',
    summary: 'Autonomous drone flight completed. Field NDVI scored 0.76 indicating high photosynthetic activity and zero weed clusters.',
    tasks: [
      'Conducted 15-minute drone aerial scan at 30m altitude',
      'Generated NDVI vigor heatmap of all 4 sectors',
      'Identified uniform crop stand with no patchy zones',
    ],
    inputsApplied: 'Drone aerial surveillance',
    category: 'inspection',
    status: 'optimal',
    icon: 'flight',
    healthPercent: 83,
  },
  {
    day: 25,
    date: 'Aug 07',
    stage: 'Vegetative Stage',
    title: 'Leaf Color Chart (LCC) Nitrogen Evaluation',
    summary: 'Evaluated top fully expanded leaves using standard 6-panel LCC. Scored 4.0 confirming sufficient nitrogen availability.',
    tasks: [
      'Tested 20 leaves under shade using IRRI Leaf Color Chart',
      'Calculated mean score of 4.0 across all sectors',
      'Confirmed no immediate urea booster needed before Day 31',
    ],
    inputsApplied: 'LCC Diagnostics',
    category: 'inspection',
    status: 'optimal',
    icon: 'palette',
    healthPercent: 83,
  },
  {
    day: 24,
    date: 'Aug 06',
    stage: 'Vegetative Stage',
    title: 'Post-Rainfall Excess Water Drainage',
    summary: 'Drained 4 cm of excess standing water following overnight monsoon rain to maintain optimal 3 cm depth.',
    tasks: [
      'Opened drainage spillways on Sector 04 boundary',
      'Prevented submergence of younger tillers',
      'Inspected field bunds for erosion or washouts',
    ],
    inputsApplied: 'Drainage water management',
    category: 'irrigation',
    status: 'action_taken',
    icon: 'rainy',
    healthPercent: 83,
  },
  {
    day: 23,
    date: 'Aug 05',
    stage: 'Vegetative Stage',
    title: 'Cono-Weeder Mechanical Inter-cultivation',
    summary: 'Operated rotary cono-weeder between transplanting rows to bury emerging weeds and aerate the root zone.',
    tasks: [
      'Inter-row weeding with rotary cono-weeder across Sector 01 & 02',
      'Incorporated weed biomass as green manure into puddle soil',
      'Enhanced root oxygenation and soil porosity',
    ],
    inputsApplied: 'Mechanical cono-weeding',
    category: 'weeding',
    status: 'action_taken',
    icon: 'agriculture',
    healthPercent: 82,
  },
  {
    day: 22,
    date: 'Aug 04',
    stage: 'Vegetative Stage',
    title: 'Field Channel Desilting & Bund Compaction',
    summary: 'Cleaned silt from water delivery trenches and reinforced boundary ridges around Sector 03 and 04.',
    tasks: [
      'Excavated sediment from main water delivery ditch',
      'Compacted earthen bunds to eliminate seepage losses',
      'Checked water level uniformity',
    ],
    inputsApplied: 'Bund maintenance',
    category: 'soil_check',
    status: 'optimal',
    icon: 'handyman',
    healthPercent: 82,
  },
  {
    day: 21,
    date: 'Aug 03',
    stage: 'Vegetative Stage',
    title: 'First Top-Dress Nitrogen Application (Urea)',
    summary: 'Applied first split of nitrogen fertilizer (Urea 25 kg/acre) to trigger rapid active tillering.',
    tasks: [
      'Broadcasted Neem-coated Urea uniformly in moist soil',
      'Kept water level shallow (2 cm) to ensure maximum fertilizer absorption',
      'Inspected tiller emergence 24 hours post-application',
    ],
    inputsApplied: 'Neem-coated Urea (60 kg total for 2.4 acres)',
    category: 'fertilizer',
    status: 'action_taken',
    icon: 'grain',
    healthPercent: 82,
  },
  {
    day: 20,
    date: 'Aug 02',
    stage: 'Vegetative Stage',
    title: 'Primary Tiller Initiation Scouting',
    summary: 'First set of primary tillers emerging from basal leaf axils. Average 3-4 tillers per hill recorded.',
    tasks: [
      'Examined 30 hills for basal tiller shoots',
      'Measured seedling root depth (8 cm)',
      'Recorded air temperature (31°C) and soil temperature (26°C)',
    ],
    inputsApplied: 'None',
    category: 'inspection',
    status: 'optimal',
    icon: 'spa',
    healthPercent: 82,
  },
  {
    day: 19,
    date: 'Aug 01',
    stage: 'Vegetative Stage',
    title: 'IoT Sensor Node Telemetry Calibration',
    summary: 'Checked solar battery voltage and soil moisture probe readings across all 4 dedicated sector nodes.',
    tasks: [
      'Calibrated Node 01 (Sector 01) through Node 04 (Sector 04)',
      'Verified moisture readings between 38% and 44%',
      'Confirmed wireless mesh sync with FarmAI cloud hub',
    ],
    inputsApplied: 'IoT telemetry maintenance',
    category: 'soil_check',
    status: 'optimal',
    icon: 'sensors',
    healthPercent: 82,
  },
  {
    day: 18,
    date: 'Jul 31',
    stage: 'Vegetative Stage',
    title: 'Transplant Shock Recovery & New Leaf Emergence',
    summary: 'Seedlings fully recovered from transplantation shock. Vigorous bright green central leaves unfolded.',
    tasks: [
      'Checked seedling mortality rate (<1.5% across 2.4 acres)',
      'Confirmed active root respiration and nutrient uptake',
      'Maintained 2 cm standing water layer',
    ],
    inputsApplied: 'Water level maintenance',
    category: 'inspection',
    status: 'optimal',
    icon: 'yard',
    healthPercent: 82,
  },
  {
    day: 17,
    date: 'Jul 30',
    stage: 'Vegetative Stage',
    title: 'Pre-Emergence Herbicide Spray (Pretilachlor)',
    summary: 'Applied selective pre-emergence herbicide to form a chemical blanket preventing grass and sedge weed seeds from germinating.',
    tasks: [
      'Applied Pretilachlor 50% EC with safener @ 500 ml/acre in standing water',
      'Maintained undisturbed 3 cm water layer for 48 hours',
      'Ensured boundary drainage was closed during application',
    ],
    inputsApplied: 'Pretilachlor 50% EC (1.2 Liters)',
    category: 'weeding',
    status: 'action_taken',
    icon: 'science',
    healthPercent: 81,
  },
  {
    day: 16,
    date: 'Jul 29',
    stage: 'Vegetative Stage',
    title: 'Early Vegetative Stage Initiation',
    summary: 'Crop established in main field. Transitioned from seedling stage to active vegetative growth.',
    tasks: [
      'Measured stand density: 33 hills per square meter',
      'Checked standing water depth (2.5 cm)',
      'Logged start of Vegetative Growth stage',
    ],
    inputsApplied: 'Canal water intake',
    category: 'inspection',
    status: 'optimal',
    icon: 'grass',
    healthPercent: 82,
  },
  {
    day: 15,
    date: 'Jul 28',
    stage: 'Germination & Seedling',
    title: 'Post-Transplant Gap Filling & Settling',
    summary: 'Walked field to fill minor transplant gaps with spare seedlings. Settled root zones with gentle watering.',
    tasks: [
      'Filled sparse spots with healthy spare nursery seedlings',
      'Verified uniform 20x15 cm hill spacing throughout',
      'Completed final nursery decommissioning',
    ],
    inputsApplied: 'Manual gap filling',
    category: 'transplantation',
    status: 'action_taken',
    icon: 'yard',
    healthPercent: 82,
  },
  {
    day: 14,
    date: 'Jul 27',
    stage: 'Germination & Seedling',
    title: 'Main Field Transplantation (Sectors 03 & 04)',
    summary: 'Transplanted remaining 1.2 acres in Sectors 03 and 04 with 14-day-old vigorous nursery seedlings.',
    tasks: [
      'Transplanted 2-3 seedlings per hill in puddle field',
      'Maintained 2 cm standing water to ease seedling anchoring',
      'Achieved full 2.4-acre field transplant coverage',
    ],
    inputsApplied: 'Transplantation labor across Sectors 03 & 04',
    category: 'transplantation',
    status: 'action_taken',
    icon: 'agriculture',
    healthPercent: 81,
  },
  {
    day: 13,
    date: 'Jul 26',
    stage: 'Germination & Seedling',
    title: 'Main Field Transplantation (Sectors 01 & 02)',
    summary: 'Commenced main field transplantation in Sectors 01 and 02 using young 13-day-old robust seedlings.',
    tasks: [
      'Transplanted seedlings with line planting technique (20x15 cm)',
      'Ensured shallow root planting depth (2-3 cm) for fast tillering',
      'Monitored puddle soil consistency',
    ],
    inputsApplied: 'Transplantation labor across Sectors 01 & 02',
    category: 'transplantation',
    status: 'action_taken',
    icon: 'agriculture',
    healthPercent: 81,
  },
  {
    day: 12,
    date: 'Jul 25',
    stage: 'Germination & Seedling',
    title: 'Nursery Seedling Pulling & Bundling',
    summary: 'Pulled 12-day-old healthy seedlings (height 18 cm, 3 leaves) from nursery beds for transplantation.',
    tasks: [
      'Flooded nursery beds prior to pulling to prevent root tear',
      'Bundled seedlings in moist gunny bags for transport',
      'Dipped seedling roots in Pseudomonas fluorescens bio-solution',
    ],
    inputsApplied: 'Pseudomonas fluorescens bio-inoculant root dip',
    category: 'transplantation',
    status: 'action_taken',
    icon: 'yard',
    healthPercent: 81,
  },
  {
    day: 11,
    date: 'Jul 24',
    stage: 'Germination & Seedling',
    title: 'Nursery Seedling Hardening',
    summary: 'Drained nursery water partially to expose seedling stems to sunlight for hardening before transplantation.',
    tasks: [
      'Drained standing water from nursery beds for 12 hours',
      'Inspected seedling stems for firmness and vigor',
      'Confirmed zero damping-off fungal symptoms',
    ],
    inputsApplied: 'Hardening aeration',
    category: 'soil_check',
    status: 'optimal',
    icon: 'sunny',
    healthPercent: 80,
  },
  {
    day: 10,
    date: 'Jul 23',
    stage: 'Germination & Seedling',
    title: 'Main Plot Puddling & Final Leveling',
    summary: 'Executed final wet tillage and wooden plank leveling across all 2.4 acres to ensure uniform water depth.',
    tasks: [
      'Second tractor puddling pass with rotavator',
      'Precision wooden plank leveling across Sectors 01-04',
      'Skimmed floating organic debris and weed residues',
    ],
    inputsApplied: 'Tractor puddling & leveling operation',
    category: 'soil_check',
    status: 'action_taken',
    icon: 'agriculture',
    healthPercent: 80,
  },
  {
    day: 9,
    date: 'Jul 22',
    stage: 'Germination & Seedling',
    title: 'Basal Fertilizer Application (DAP + MOP + Zinc)',
    summary: 'Incorporated basal nutrients into puddled soil prior to final plank leveling.',
    tasks: [
      'Applied Di-Ammonium Phosphate (DAP 50 kg/acre)',
      'Applied Muriate of Potash (MOP 20 kg/acre)',
      'Applied Zinc Sulphate 21% (10 kg/acre)',
    ],
    inputsApplied: 'DAP (120 kg) + MOP (48 kg) + Zinc Sulphate (24 kg)',
    category: 'fertilizer',
    status: 'action_taken',
    icon: 'grain',
    healthPercent: 80,
  },
  {
    day: 8,
    date: 'Jul 21',
    stage: 'Germination & Seedling',
    title: 'Main Field Wet Puddling Commenced',
    summary: 'Flooded main field with 5 cm canal water and commenced initial tractor puddling to destroy soil pores.',
    tasks: [
      'Initial wet plowing in Sectors 01 and 02',
      'Closed drainage outlets to retain puddled water',
      'Tested nursery seedlings (2.5 leaves, 14 cm height)',
    ],
    inputsApplied: 'Tractor wet plowing',
    category: 'soil_check',
    status: 'action_taken',
    icon: 'agriculture',
    healthPercent: 80,
  },
  {
    day: 7,
    date: 'Jul 20',
    stage: 'Germination & Seedling',
    title: 'Nursery Root Anchoring & 2-Leaf Stage',
    summary: 'Seedlings reached 2-leaf stage with healthy white root development. Leaf color vibrant green.',
    tasks: [
      'Inspected seedling root system in nursery beds',
      'Maintained 2 cm shallow water film to prevent soil baking',
      'Confirmed absence of thrips or armyworm in nursery',
    ],
    inputsApplied: 'Nursery water maintenance',
    category: 'inspection',
    status: 'optimal',
    icon: 'yard',
    healthPercent: 79,
  },
  {
    day: 6,
    date: 'Jul 19',
    stage: 'Germination & Seedling',
    title: 'Nursery Foliar Nutrient Spray',
    summary: 'Sprayed mild foliar Zinc Sulphate (0.5%) + Urea (1%) to accelerate early seedling photosynthesis.',
    tasks: [
      'Applied mild micronutrient foliar spray across nursery beds',
      'Checked nursery bed drainage after spray',
      'Measured ambient nursery temperature (30°C)',
    ],
    inputsApplied: 'Zinc Sulphate (100g) + Urea (200g) in 20L water',
    category: 'fertilizer',
    status: 'action_taken',
    icon: 'science',
    healthPercent: 79,
  },
  {
    day: 5,
    date: 'Jul 18',
    stage: 'Germination & Seedling',
    title: 'First Leaf Spike Emergence (Coleoptile Stage)',
    summary: 'First green leaf spikes unfurled above soil surface across >90% of nursery beds.',
    tasks: [
      'Confirmed uniform coleoptile emergence in nursery',
      'Measured soil moisture (48%) in nursery bed profile',
      'Maintained shallow water film at dusk',
    ],
    inputsApplied: 'Shallow nursery watering',
    category: 'inspection',
    status: 'optimal',
    icon: 'spa',
    healthPercent: 79,
  },
  {
    day: 4,
    date: 'Jul 17',
    stage: 'Germination & Seedling',
    title: 'Nursery Water Film Maintenance',
    summary: 'Maintained thin 1-2 cm water film over nursery beds to soften soil and aid vertical shoot growth.',
    tasks: [
      'Gentle inlet flooding across nursery beds',
      'Checked for bird predation or surface crusting',
      'Installed reflective bird ribbons around nursery perimeter',
    ],
    inputsApplied: 'Fresh well water misting',
    category: 'irrigation',
    status: 'optimal',
    icon: 'water_drop',
    healthPercent: 78,
  },
  {
    day: 3,
    date: 'Jul 16',
    stage: 'Germination & Seedling',
    title: 'Radicle Protrusion & Sprout Scouting',
    summary: 'Radicle protrusion observed in 88% of sown seeds. White tap rootlets anchoring securely into mud.',
    tasks: [
      'Scouted seed beds for radicle extension and sprout uniformity',
      'Checked surface moisture level (moist, not inundated)',
      'Verified zero fungal mold on sown seeds',
    ],
    inputsApplied: 'None',
    category: 'inspection',
    status: 'optimal',
    icon: 'yard',
    healthPercent: 78,
  },
  {
    day: 2,
    date: 'Jul 15',
    stage: 'Germination & Seedling',
    title: 'Seed Bed Moisture Monitoring & GPS Boundary Setup',
    summary: 'Walked field boundary to record 2.4-acre GPS polygon. Light surface misting applied to nursery beds.',
    tasks: [
      'Recorded 5 GPS polygon perimeter points for Field 01 (2.4 Acres)',
      'Misted nursery beds with fine spray rose to preserve moisture',
      'Calibrated boundary coordinates in FarmAI',
    ],
    inputsApplied: 'GPS recording & light nursery misting',
    category: 'soil_check',
    status: 'optimal',
    icon: 'map',
    healthPercent: 78,
  },
  {
    day: 1,
    date: 'Jul 14',
    stage: 'Germination & Seedling',
    title: 'Sowing Day & Seed Treatment (Paddy BPT 5204)',
    summary: 'Treated pre-germinated certified Paddy BPT 5204 seeds with Carbendazim fungicide and broadcasted onto raised nursery beds.',
    tasks: [
      'Seed treatment with Carbendazim 50% WP @ 2g/kg seed for disease prevention',
      'Incubated seeds in damp gunny bags for 24h sprouting',
      'Broadcasted sprouted seeds uniformly on raised puddle nursery beds (25 kg/acre)',
      'Logged sowing date (2026-07-14) in FarmAI crop cycle tracker',
    ],
    inputsApplied: 'Paddy BPT 5204 Seeds (60 kg) + Carbendazim (120g)',
    category: 'sowing',
    status: 'action_taken',
    icon: 'grass',
    healthPercent: 78,
  },
];

export const INITIAL_FIELD_BOUNDARY: FieldBoundary = {
  id: 'field-01',
  name: 'Paddy Main Plot - Sector East',
  acres: 2.4,
  isRecorded: true,
  savedAt: '2026-07-15 10:30 AM',
  points: [
    { x: 20, y: 80, lat: 14.5012, lng: 79.9812 },
    { x: 30, y: 30, lat: 14.5045, lng: 79.9825 },
    { x: 70, y: 20, lat: 14.5050, lng: 79.9870 },
    { x: 85, y: 60, lat: 14.5020, lng: 79.9885 },
    { x: 60, y: 90, lat: 14.4995, lng: 79.9850 },
  ],
};

export const INITIAL_FIELD_BOUNDARY: FieldBoundary = INITIAL_FIELDS[0].boundary;


export const INITIAL_CROP_HISTORY: CropHistoryRecord[] = [
  {
    id: 'ch-2025',
    yearLabel: 'Paddy 2025',
    cropName: 'Paddy (BPT 5204)',
    expectedYieldTons: 4.8,
    actualYieldTons: 4.1,
    efficiencyPercent: 85,
    yieldLossFactors: [
      { factorName: 'Pest Infestation (Stem Borer)', icon: 'bug_report', lossTons: 0.3, color: 'bg-error' },
      { factorName: 'Irrigation Deficit (Mid-season)', icon: 'water_drop', lossTons: 0.2, color: 'bg-tertiary' },
      { factorName: 'Fungal Infection (Brown Spot)', icon: 'coronavirus', lossTons: 0.2, color: 'bg-outline' },
    ],
  },
  {
    id: 'ch-2024',
    yearLabel: 'Cotton 2024',
    cropName: 'Bt Cotton',
    expectedYieldTons: 3.2,
    actualYieldTons: 2.9,
    efficiencyPercent: 90,
    yieldLossFactors: [
      { factorName: 'Bollworm Attack', icon: 'bug_report', lossTons: 0.2, color: 'bg-error' },
      { factorName: 'Unseasonal Rainfall', icon: 'rainy', lossTons: 0.1, color: 'bg-tertiary' },
    ],
  },
];

export { EXPANDED_MARKET_RATES as INITIAL_MARKET_RATES } from './marketService';
export { COMPREHENSIVE_CROP_CATALOG as SUITABLE_CROP_SUGGESTIONS } from './cropSuggestionService';

export const ANDHRA_PRADESH_MAJOR_CROPS = [
  'Paddy',
  'Maize',
  'Cotton',
  'Groundnut',
  'Chillies',
  'Tobacco',
  'Sugarcane',
  'Red Gram',
  'Bengal Gram',
  'Black Gram',
  'Green Gram',
  'Jowar',
  'Bajra',
  'Ragi',
  'Korra',
  'Oil Palm',
  'Sunflower',
  'Turmeric',
  'Mango',
];
